#!/bin/bash
#PBS -P VUR
#PBS -l select=1:ncpus=4:ngpus=1:mem=16GB
#PBS -l walltime=00:05:00
#PBS -j oe

cd /home/jshe2377/neural-rgbd-torch

module load python/3.8.2 magma/2.5.3 openmpi-gcc/3.1.5
source /home/jshe2377/NeuS/neus/bin/activate
module load cuda/10.2.89

cd external/NumpyMarchingCubes
python setup.py install
cd /home/jshe2377/neural-rgbd-torch
python optimize.py --config configs/thin_geo.txt